"""Constants, API URLs, cache TTLs, and station data for SEPTA MCP server."""

SEPTA_BASE_URL = "https://www3.septa.org/api"

# Endpoint URLs
NEXT_TO_ARRIVE_URL = f"{SEPTA_BASE_URL}/NextToArrive/index.php"
ARRIVALS_URL = f"{SEPTA_BASE_URL}/Arrivals/index.php"
TRAIN_VIEW_URL = f"{SEPTA_BASE_URL}/TrainView/index.php"
TRANSIT_VIEW_URL = f"{SEPTA_BASE_URL}/TransitView/index.php"
ALERTS_URL = f"{SEPTA_BASE_URL}/Alerts/get_alert_data.php"
BUS_DETOURS_URL = f"{SEPTA_BASE_URL}/BusDetours/"

# Cache TTLs (seconds)
CACHE_TTL_TRAIN_VIEW = 30
CACHE_TTL_ARRIVALS = 30
CACHE_TTL_NEXT_TO_ARRIVE = 45
CACHE_TTL_TRANSIT_VIEW = 30
CACHE_TTL_ALERTS = 120

# Default counts
DEFAULT_DEPARTURE_COUNT = 5
DEFAULT_ARRIVALS_COUNT = 10

# HTTP client settings
HTTP_TIMEOUT = 15.0

# All SEPTA Regional Rail station names (canonical, as accepted by API)
REGIONAL_RAIL_STATIONS: frozenset[str] = frozenset({
    "30th Street Station",
    "49th Street",
    "Airport Terminal A",
    "Airport Terminal B",
    "Airport Terminals C & D",
    "Airport Terminals E & F",
    "Allen Lane",
    "Ambler",
    "Angora",
    "Ardmore",
    "Ardsley",
    "Bala",
    "Bethayres",
    "Bridesburg",
    "Bristol",
    "Bryn Mawr",
    "Carpenter",
    "Chalfont",
    "Chelten Avenue",
    "Cheltenham",
    "Chester Transportation Center",
    "Chestnut Hill East",
    "Chestnut Hill West",
    "Churchmans Crossing",
    "Claymont",
    "Clifton-Aldan",
    "Colmar",
    "Conshohocken",
    "Cornwells Heights",
    "Crestmont",
    "Croydon",
    "Crum Lynne",
    "Curtis Park",
    "Cynwyd",
    "Darby",
    "Daylesford",
    "Delaware Valley College",
    "Devon",
    "Doylestown",
    "East Falls",
    "Eastwick",
    "Eddington",
    "Eddystone",
    "Elkins Park",
    "Elm Street",
    "Elwyn",
    "Exton",
    "Fern Rock Transportation Center",
    "Fernwood-Yeadon",
    "Folcroft",
    "Forest Hills",
    "Fortuna",
    "Fort Washington",
    "Fox Chase",
    "Germantown",
    "Glenolden",
    "Glenside",
    "Gravers",
    "Gwynedd Valley",
    "Hatboro",
    "Haverford",
    "Highland",
    "Highland Avenue",
    "Holmesburg Junction",
    "Ivy Ridge",
    "Jefferson Station",
    "Jenkintown-Wyncote",
    "Langhorne",
    "Lansdale",
    "Lansdowne",
    "Lawndale",
    "Levittown",
    "Link Belt",
    "Malvern",
    "Manayunk",
    "Marcus Hook",
    "Media",
    "Melrose Park",
    "Merion",
    "Miquon",
    "Morton",
    "Moylan-Rose Valley",
    "Mt. Airy",
    "Narberth",
    "Neshaminy Falls",
    "Newark",
    "Noble",
    "Norristown Transportation Center",
    "North Broad",
    "North Hills",
    "North Philadelphia",
    "North Wales",
    "Norwood",
    "Olney",
    "Oreland",
    "Overbrook",
    "Paoli",
    "Penllyn",
    "Penn Medicine Station",
    "Pennbrook",
    "Philmont",
    "Primos",
    "Prospect Park",
    "Queen Lane",
    "Radnor",
    "Ridley Park",
    "Rosemont",
    "Roslyn",
    "Rydal",
    "Ryers",
    "Secane",
    "Sedgwick",
    "Sharon Hill",
    "Somerton",
    "Spring Mill",
    "St. Davids",
    "St. Martins",
    "Stenton",
    "Strafford",
    "Suburban Station",
    "Swarthmore",
    "Tabor",
    "Tacony",
    "Temple University",
    "Thorndale",
    "Torresdale",
    "Trenton Transit Center",
    "Trevose",
    "Tulpehocken",
    "Villanova",
    "Wallingford",
    "Warminster",
    "Washington Lane",
    "Wayne",
    "Wayne Junction",
    "West Trenton",
    "Whitford",
    "Willow Grove",
    "Wilmington",
    "Winslow Junction",
    "Wissahickon",
    "Wister",
    "Woodbourne",
    "Wyndmoor",
    "Wynnefield Avenue",
    "Wynnewood",
    "Yardley",
})

REGIONAL_RAIL_LINES: frozenset[str] = frozenset({
    "Airport",
    "Chestnut Hill East",
    "Chestnut Hill West",
    "Cynwyd",
    "Fox Chase",
    "Lansdale/Doylestown",
    "Manayunk/Norristown",
    "Media/Elwyn",
    "Paoli/Thorndale",
    "Trenton",
    "Warminster",
    "West Trenton",
    "Wilmington/Newark",
})

# Common shorthand/aliases → canonical station name
STATION_ALIASES: dict[str, str] = {
    "suburban": "Suburban Station",
    "jefferson": "Jefferson Station",
    "market east": "Jefferson Station",
    "30th street": "30th Street Station",
    "30th st": "30th Street Station",
    "thirtieth street": "30th Street Station",
    "university city": "Penn Medicine Station",
    "penn medicine": "Penn Medicine Station",
    "temple": "Temple University",
    "temple u": "Temple University",
    "airport": "Airport Terminal B",
    "airport a": "Airport Terminal A",
    "airport b": "Airport Terminal B",
    "airport c": "Airport Terminals C & D",
    "airport d": "Airport Terminals C & D",
    "airport e": "Airport Terminals E & F",
    "airport f": "Airport Terminals E & F",
    "phl": "Airport Terminal B",
    "trenton": "Trenton Transit Center",
    "chester": "Chester Transportation Center",
    "norristown": "Norristown Transportation Center",
    "norristown tc": "Norristown Transportation Center",
    "fern rock": "Fern Rock Transportation Center",
    "fern rock tc": "Fern Rock Transportation Center",
    "chestnut hill e": "Chestnut Hill East",
    "chestnut hill w": "Chestnut Hill West",
    "che": "Chestnut Hill East",
    "chw": "Chestnut Hill West",
    "bryn mawr": "Bryn Mawr",
    "wilmington": "Wilmington",
    "newark": "Newark",
    "doylestown": "Doylestown",
    "lansdale": "Lansdale",
    "warminster": "Warminster",
    "west trenton": "West Trenton",
    "fox chase": "Fox Chase",
    "paoli": "Paoli",
    "thorndale": "Thorndale",
    "exton": "Exton",
    "malvern": "Malvern",
    "devon": "Devon",
    "wayne": "Wayne",
    "ardmore": "Ardmore",
    "media": "Media",
    "elwyn": "Elwyn",
    "north broad": "North Broad",
    "north philly": "North Philadelphia",
    "north philadelphia": "North Philadelphia",
    "wayne junction": "Wayne Junction",
    "manayunk": "Manayunk",
    "conshohocken": "Conshohocken",
    "jenkintown": "Jenkintown-Wyncote",
    "wyncote": "Jenkintown-Wyncote",
    "glenside": "Glenside",
    "ambler": "Ambler",
    "narberth": "Narberth",
    "overbrook": "Overbrook",
    "haverford": "Haverford",
    "villanova": "Villanova",
    "rosemont": "Rosemont",
    "radnor": "Radnor",
    "swarthmore": "Swarthmore",
    "ridley park": "Ridley Park",
    "marcus hook": "Marcus Hook",
    "cynwyd": "Cynwyd",
    "bala": "Bala",
    "eastwick": "Eastwick",
}

# Map line short codes (used in alert route_id) → line display names
RAIL_LINE_ALERT_IDS: dict[str, str] = {
    "rr_route_air": "Airport",
    "rr_route_che": "Chestnut Hill East",
    "rr_route_chw": "Chestnut Hill West",
    "rr_route_cyn": "Cynwyd",
    "rr_route_fox": "Fox Chase",
    "rr_route_lan": "Lansdale/Doylestown",
    "rr_route_nor": "Manayunk/Norristown",
    "rr_route_med": "Media/Elwyn",
    "rr_route_pao": "Paoli/Thorndale",
    "rr_route_tren": "Trenton",
    "rr_route_warm": "Warminster",
    "rr_route_wtren": "West Trenton",
    "rr_route_wil": "Wilmington/Newark",
}

# Reverse lookup: line name → alert route_id
LINE_TO_ALERT_ID: dict[str, str] = {v: k for k, v in RAIL_LINE_ALERT_IDS.items()}

# Subway / other transit alert IDs
TRANSIT_ALERT_IDS: dict[str, str] = {
    "bsl": "Broad Street Line",
    "mfl": "Market Frankford Line",
    "nhsl": "Norristown High Speed Line",
}
